config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :politicians
resources :donors
resources :contributions
resources :static_pages
resources :sessions
get '/login', to: 'sessions#new'
post 'login', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :donor
  belongs_to :politician
end

app/models/donor.rb
class Donor < ApplicationRecord

has_many :contributions
has_many :politicians, through: :contributions
validates :name,  presence: true, length: { maximum: 50 }
end

app/models/policy.rb
class Policy < ApplicationRecord
    has_many :politician_policies
    has_many :politicians, through: :politician_policies
end

app/models/politician.rb
class Politician < ApplicationRecord
    has_many :contributions
    has_many :donors, through: :contributions
    has_many :politician_policies
    has_many :policies, through: :politician_policies

    def sum
        total = 0
         self.contributions.each do |contribution|
            total += contribution.amount
         end
         total
    end 

end

app/models/politician_policy.rb
class PoliticianPolicy < ApplicationRecord
  belongs_to :politician
  belongs_to :policy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

    def new
        @contribution = Contribution.find_by(params[:id])
    end
    def create
        @contribution = Contribution.create(params[:id])
    end

    private
    def contribution_params
        params.require(:contribution).permit(:politician_id, :amount, :password, :password_confirmation)

    end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
    def show
        @donor = Donor.find(params[:id])
    end

    def new 
    end

    def create 
        
    end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
    def index
        @politicians = Politician.all
    end
    def show
      @politician = Politician.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

    def create
        if @donor && @donor.password = (params[:session][:password])
        @donor = Donor.find_by(username: params[:session][:username].downcase)
        flash[:success] = "Login Successful"
        redirect_to donor_path(@donor)
        else
            flash[:danger] = "Login Unsuccessful"
            render:new
        end
    end

    def destroy
        
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contributions/new.html.erb
<div class="container">
<h4>Donate to your candidate</h4>


<%= form_for @contribution do |f| %>
<%= f.collection_select :politician_id, Politician.all, :id, :name,{ prompt: "Choose a Politician" }, class: "browser-default"  %>
<%= f.label :Amount %>:
<%= f.text_field :amount %> <br>
<%= f.submit "Donate", class: "btn waves-effect waves-light"%>
<% end %>
</div>

app/views/donors/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>


    <%= form_with(model: @donor, local: true) do |f| %> 
    <%= f.label :name %>:
    <%= f.text_field :name %> <br>
    <%= f.label :email %>:
    <%= f.email_field :email %> <br>
    <%= f.label :password %>:
    <%= f.password_field :password %> <br>
    <%= f.label :password_confirmation, "Confirmation" %> :
    <%= f.password_field :password_confirmation %> <br>
    <%= f.submit "Create my account" %> 
    <% end %>
  </div>
</div>

app/views/donors/show.html.erb
<div class="container">
<h4>My Profile</h4>
<p>Name: <%= @donor.name %></h4>
<p>Registered: <%= @donor.registered %></p>
<p>Total Contributions:</p>

<h4>My Contributions</h4>

<% @donor.contributions.each do |contribution| %>
<table>
  <thead>
    <tr>
        <th> </th>
        <th></th>
        <th></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= image_tag contribution.politician.image, style: 'width:40%'%> </td>
      <td><%= link_to contribution.politician.name, politician_path(contribution.politician) %></td>
      <td> $<%= contribution.amount %></td>
    </tr>
  </tbody>
</table>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BribeStarter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">BribeStarter</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Politicians", politicians_path %></li>
          <li><a href="badges.html">My Profile</a></li>
          <li><a href="collapsible.html">JavaScript</a></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/politicians/index.html.erb
<div class="container">
<h1 class="center-align">Politicians</h1>

<% @politicians.each do |crook| %>
<span>
<div class="row"  style="display: inline">
  <div class="col s6">
    <div class="card">
      <div class="card-image">
        <%= image_tag crook.image, style: 'width:100%'%> 
        <span class="card-title"><%=link_to crook.name, politician_path(crook)%></span>
      </div>
      <div class="card-content">
        <p><%= crook.bio %></p>
      </div>
      <div class="card-action">
        <%= link_to "Learn More", politician_path(crook) %>
      </div>
    </div>
  </div>
</div>
</span>

<%end%>
</div>

app/views/politicians/show.html.erb
<div class="container">
  <%= image_tag @politician.image, :class => "materialboxed", style: 'width:50%' %> <br>

  <%= link_to "Donate", new_contribution_path, class: "waves-effect waves-light btn-large" %>

  <h1><%= @politician.name %></h1>
  <h4>Contributions: $<span class="blue-text text-darken-2"> <%= @politician.sum %></span></h4>


  <ul>
    <li>Political Affiliation: <%= @politician.registered %></li>
    <li>Title: <%= @politician.office %></li>
    <li>Biography: <%= @politician.bio %></li>
  </ul>
  <h2>Causes</h2>

  <ul class="collapsible">
    <% @politician.policies.each do |policy| %>
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i><%= policy.name %></div>
      <div class="collapsible-body"><span>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Praesentium
 reprehenderit ullam illo aperiam tempora quaerat.</span></div>
      </li>
    <% end %>
  </ul>

</div>

app/views/static_pages/home.html.erb
<h1>BribeStarter</h1>
<p>Influencing the world, one election at a time.</p>

<h2>"Bribe a politician today!"</h2>
<div>
  <h2>Log In</h2>

  <%= form_for(model: @donor, local: true) do |f| %> <%= f.label :username %>:
  <%= f.text_field :username %> <br />
  <%= f.label :password %>: <%= f.password_field :password %> <br />
  <%= f.label :password_confirmation, "Confirmation" %> : <%= f.password_field
  :password_confirmation %> <br />
  <%= f.submit "Create my account" %> <% end %> <% link_to "Not a member?
  Register here!", donor_new_path %>
</div>